# Generated by Django 5.1.2 on 2024-10-30 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_creation',
            field=models.TimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo do Evento'),
        ),
    ]
