# Generated by Django 5.1.2 on 2024-10-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_user_alter_event_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='local',
            field=models.CharField(default=1, max_length=255, verbose_name='Local do Evento'),
            preserve_default=False,
        ),
    ]
